# Generated by Django 4.2 on 2025-07-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('user_type', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=10)),
                ('terms_and_conditions', models.BooleanField(default=False)),
            ],
        ),
    ]
