# Generated by Django 4.2 on 2025-07-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_customuser_user_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('install_date', models.DateField(auto_now_add=True)),
                ('capacity_kwp', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('tier_field_until', models.CharField(default='0', max_length=10)),
                ('image_field', models.ImageField(blank=True, null=True, upload_to='device_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='app2.customuser')),
            ],
        ),
    ]
