# Generated by Django 4.2 on 2025-07-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nid_number', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('savings account', 'Savings Account'), ('current account', 'Current Account')], max_length=20)),
                ('branch_code', models.CharField(max_length=150)),
                ('bank_name', models.CharField(choices=[('brac_bank', 'BRAC Bank'), ('dutch_bangla_bank', 'Dutch-Bangla Bank'), ('islami_bank', 'Islami Bank'), ('city_bank', 'City Bank'), ('prime_bank', 'Prime Bank'), ('southeast_bank', 'Southeast Bank'), ('standard_chartered', 'Standard Chartered')], max_length=50)),
                ('terms_acceptde', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='app2.customuser')),
            ],
        ),
    ]
