# Generated by Django 4.2 on 2025-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_bankinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinformation',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings account', 'Savings Account'), ('current account', 'Current Account')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('brac_bank', 'BRAC Bank'), ('dutch_bangla_bank', 'Dutch-Bangla Bank'), ('islami_bank', 'Islami Bank'), ('city_bank', 'City Bank'), ('prime_bank', 'Prime Bank'), ('southeast_bank', 'Southeast Bank'), ('standard_chartered', 'Standard Chartered')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='branch_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='nid_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bankinformation',
            unique_together={('custom_user', 'account_number')},
        ),
    ]
