# Generated by Django 4.2 on 2025-08-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_alter_bankinformation_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankinformation',
            old_name='terms_acceptde',
            new_name='terms_accepted',
        ),
    ]
