# Generated by Django 4.2 on 2025-08-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_rename_terms_acceptde_bankinformation_terms_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=30, null=True)),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='brand_images/')),
            ],
        ),
    ]
