# Generated by Django 4.2 on 2025-08-21 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0010_brandinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('operations_date', models.DateField(blank=True, null=True)),
                ('custom_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_info', to='app2.customuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
