# Generated by Django 4.2 on 2025-08-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_deviceinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinformation',
            name='brand_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_info', to='app2.brandinformation'),
        ),
    ]
