# Generated by Django 4.2 on 2025-08-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_devicelocation_deviceinformation_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinformation',
            name='Check',
            field=models.CharField(blank=True, choices=[('confirm', 'Confirm'), ('pending', 'Pending')], default='pending', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deviceinformation',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=10, null=True),
        ),
    ]
