# Generated by Django 4.2 on 2025-08-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_deviceinformation_check_deviceinformation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinformation',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
