# Generated by Django 4.2 on 2025-08-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_deviceinformation_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('inverter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inverters', to='app2.deviceinformation')),
            ],
        ),
    ]
