# Generated by Django 4.2 on 2025-08-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_inverter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inverter',
            old_name='inverter',
            new_name='device',
        ),
        migrations.RemoveField(
            model_name='deviceinformation',
            name='device_location',
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app2.deviceinformation'),
        ),
    ]
