# Generated by Django 4.2 on 2025-08-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0017_rename_inverter_inverter_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inverter',
            old_name='capacity',
            new_name='inverter_capacity',
        ),
    ]
