# Generated by Django 4.2 on 2025-07-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dept',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('EEE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering')], default='CSE', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='Unknown Name', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
