# Generated by Django 4.2 on 2025-05-02 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=15, unique=True)),
                ('dept', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('EEE', 'Electrical & Electronic Engineering'), ('BBA', 'Business Administration'), ('ENG', 'English Literature')], max_length=50)),
                ('address', models.TextField()),
                ('profile_pic', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
